### PR TITLE
Add initial sequelize migration file

### PR DESCRIPTION
**Pull request by letusfly85**
Summary:
---

- export `sequelize initial migration file` following way example.

```bash
./bin/seq-ei -i -H localhost -u root -p password -d database_name --output $PWD/migrations -m mysql -e js
```

### CODE REVIEW

**Comment by shaunplumb** [comment]
Just as a heads up I have added a few items in my pull request to the export for certain data types (decimal and enum) for it to work properly.  You may want this added to your as well.

**Comment by letusfly85** [comment]
@shaunplumb 

Thank you, I want to get your two commits.
Don't you create a PR?
https://github.com/shaunplumb/sequelize-db-export-import/commits/master


https://github.com/shaunplumb/sequelize-db-export-import/commit/a250361effa47f0d7b988547f223707c09cbfd38
https://github.com/shaunplumb/sequelize-db-export-import/commit/3cffb92c5d8b54f5ee41476fddecdc7dc2ff06f3

**Comment by boiawang** [comment]
ci error

**Comment by letusfly85** [comment]
@boiawang 

>ci error

Thank you for checking.
I modified.

**Comment by shaunplumb** [comment]
If you look at line 126 of yours for the type of integer the other export has 2 new types added for enum and decimal that will help with the export.  Not sure if you want to add that as well.  Should be line 132-137 of the other export file.

**Comment by letusfly85** [comment]
@shaunplumb 

Thank you, I added two new types 👍

**Review by boiawang — COMMENTED** [review]
reviewed

**Comment by letusfly85** [comment]
@boiawang

Thank you !

**Pull request merged**
